#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2022 Jarkko Sakkinen <jarkko.sakkinen@iki.fi>

function do_exit
{
  rm -f "$ARCHIVE"
  rm -f "$ARCHIVE.bz2"
  exit $1
}

function do_sigint
{
  do_exit 0
}

trap do_sigint SIGINT

if [ "$#" -ne 3 ]; then
  echo "`basename $0` NAME SOURCE DEST" >&2
  do_exit 1
fi

NAME="$1"
SOURCE=`realpath $2`
DEST="$3"

if [[ "$NAME" =~ [^a-zA-Z0-9] ]]; then
  echo NAME must contain only alphanumeric characters. >&2
  do_exit 1
fi

if [ ! -d "$SOURCE" ]; then
  echo SOURCE must be a directory. >&2
  do_exit 1
fi

if [ ! -d "$DEST" ]; then
  echo DEST must be a directory. >&2
  do_exit 1
fi

# ISO 8601
ARCHIVE="$DEST/${NAME}_${HOSTNAME}_$(date -Im).tar"

if [ -e "$ARCHIVE" ]; then
  echo "$ARCHIVE already exists." >&2
  do_exit 1
fi

SOURCE_PATHS="$(</dev/stdin)"

echo -n [ >&2
while IFS= read -r; do
  if [ ! -e "$SOURCE/$REPLY" ]; then
    echo >&2
    echo "'$SOURCE/$REPLY' does not exist" >&2
    do_exit 1
  fi
  tar rf $ARCHIVE -C "$SOURCE" "$REPLY" || do_exit 1
  echo -n '=' >&2
done <<< "$SOURCE_PATHS"
echo ] >&2

pv $ARCHIVE | bzip2 > $ARCHIVE.bz2 || do_exit 1
rm -f "$ARCHIVE"
